### ISSUE TITLE
Does nothing after putting the paths in

### ISSUE THREAD

**Issue by greennhead** [oldsportsgit/GUIDcorrector#4]
it either does nothing, or closes after i put all 3 paths in

the paths used:
...\ExportedProject\Assets\Scripts\Unity.TextMeshPro
...\ExportedProject\Library\PackageCache\com.unity.textmeshpro@3.0.9
...\ExportedProject\Assets

**Comment by IceburgLettuce17** [comment]
same issue

**Comment by ningengit** [comment]
dunno how that is possible and dunno how to debug this
